### ISSUE TITLE
改了原项目的什么？

### ISSUE THREAD

**Issue by disanda** [zh-plus/video-to-pose3D#15]

**Comment by disanda** [comment]
你这和原项目有说明区别？改了更方便抽取单张的pose吗?

**Comment by disanda** [comment]
ok

**Comment by zh-plus** [comment]
原项目是指facebook的videopose吗？

是的话请参看https://github.com/zh-plus/video-to-pose3D#acknowledgement 和 https://github.com/zh-plus/video-to-pose3D#coming-soon
