### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by XKMar** [zh-plus/video-to-pose3D#17]
Traceback (most recent call last):
  File "videopose.py", line 164, in <module>
    inference_video('outputs/gait.mp4', 'alpha_pose')
  File "videopose.py", line 160, in inference_video
    main(args)
  File "videopose.py", line 69, in main
    keypoints = detector_2d(video_name)
  File "/home/makang/code/Pose/video-to-pose3D/joints_detectors/Alphapose/gene_npz.py", line 63, in generate_kpts
    kpts = np.array(kpts).astype(np.float32)
ValueError: setting an array element with a sequence.

**Comment by zh-plus** [comment]
Can you print the `kpts`? I can't reproduce this error without your video.

**Comment by XKMar** [comment]
> Can you print the `kpts`? I can't reproduce this error without your video.

I have found the reasons: if the “kpts[-1] = None”，there will meet the problems. 
In "video-to-pose3D/joints_detectors/Alphapose/gene_npz.py" line 57:
it should be:
for n in no_person:
    if kpts[-1] is not None:
        kpts[n] = kpts[-1]
    else:
        kpts[n] = kpts[n-1]

to prevent "kpts[-1] = None"

**Comment by zh-plus** [comment]
Yeah, I forgot the situation that no person appears in the last frame.

This statement can be simplified using
`kpts[n] = kpts[-1] if kpts[-1] else kpts[n-1]`

Would you make a pull request on this edge case?
