### ISSUE TITLE
Issue while running a sample video

### ISSUE THREAD

**Issue by basicvisual** [zh-plus/video-to-pose3D#2]
Hi I was trying to run `videopose.py` using python 3.7 in virtual env using `ubuntu 18.04`. The command i used was as follows 

`python3.7 videopose.py --video ./outputs/kunkun_cut.mp4 ` which results in the following  error 

```
Traceback (most recent call last):
  File "videopose.py", line 174, in <module>
    inference_video('outputs/dance.mp4', 'alpha_pose')
  File "videopose.py", line 163, in inference_video
    main(args)
  File "videopose.py", line 67, in main
    split_video(args.viz_video)
  File "/sandbox/video-to-pose3D/common/utils.py", line 154, in split_video
    saved_path = os.path.dirname(save_path)
UnboundLocalError: local variable 'save_path' referenced before assignment
```
I am using `hrnet` as 2D detector .

**Comment by zh-plus** [comment]
First of all, you don't need to specify `--video` in your command line. `python3.7 videopose.py` is enough because the `args.viz_video` will be overloaded by the first parameter of `inference_video`.

The Error is caused by the
```python
i = 1
while True:
    grabbed, frame = stream.read()

    if not grabbed:
        print(f'Split totally {i + 1} images from video.')
        break

    save_path = f'{save_folder}/output{str(i).zfill(length)}.png'
    cv2.imwrite(save_path, frame)
    i += 1
```

in which `stream.read()` don't read any frame. The while loop `break` directly.

You can run the `./test/opencv_capture_test.py` to check whether the `cv2.VideoCapture(path)` works properly or not. Don't forget to change the `path` to your video path, and check if there are any problems of the working directory of python interpreter.

If it runs properly, the `args.viz_video` must be changed because of the `args.viz_video = video_path` in `inference_video`. Try to directly change the first parameter of `inference_video` in
```python
if __name__ == '__main__':
    inference_video('outputs/dance.mp4', 'alpha_pose')
```
to your absolute video path.

By the way, I'm developing this project using PyCharm. It's recommended that using the same IDE to run the script instead of the command line.

**Comment by basicvisual** [comment]
Hi thanks for your clarification,
i did as you had suggested and tested the script `./test/opencv_capture_test.py`  and it worked perfectly.  However i think there are some error in importing the `hrnet` model . Because i changed the following in `videopose.py`


`    inference_video('/home/sandbox/video-to-pose3D/outputs/kunkun_cut.mp4', 'hr_pose')` 
It gave the following error 

```
Traceback (most recent call last):
  File "videopose.py", line 174, in <module>
    inference_video('/home/pramah/sandbox/video-to-pose3D/outputs/kunkun_cut.mp4', 'hr_pose')
  File "videopose.py", line 163, in inference_video
    main(args)
  File "videopose.py", line 62, in main
    detector_2d = get_detector_2d(args.detector_2d)
  File "videopose.py", line 50, in get_detector_2d
    return detector_map[detector_name]()
  File "videopose.py", line 39, in get_hr_pose
    from joints_detectors.hrnet.pose_estimation.video import generate_kpts as hr_pose
  File "/home/sandbox/video-to-pose3D/joints_detectors/hrnet/pose_estimation/video.py", line 15, in <module>
    from lib.config import cfg
ModuleNotFoundError: No module named 'lib'

```
I seemed to have followed your instructions to place pretrained weights and yolo module . I  think there is just a dependency some where

**Comment by zh-plus** [comment]
As is said in my README
>1. If you're using PyCharm, mark ./joints_detectors/Alphapose, ./joints_detectors/hrnet and ./pose_trackers as source root.
>2. If your're trying to run in command line, add these paths mentioned above to the sys.path at the head of ./videopose.py

The bug is caused by the fact that these paths are not in your `sys.path`.
I've updated my code to add them into `sys.path` manually. You can pull the project and try again.

**Comment by basicvisual** [comment]
I will try again  . Sorry that i have missed it .

**Comment by basicvisual** [comment]
Hello again , I seem to move forward but seem to have some issues with `CUDA ` . I have an inbuilt GPU and i have setup the requirements by creating a `virtual env` . I double checked if `torch device`is detected and apparently it is .  
```
print torch.cuda.is_available()
true
```
And the error i get is in the python package as follows .Do you have a certain version of torch ? I have the following packages installed in my virtual enviroment. I am using ùbuntu18.04` 

```
cycler (0.10.0)
ffmpeg (1.4)
kiwisolver (1.1.0)
matplotlib (3.1.1)
nibabel (2.5.0)
numpy (1.17.0)
opencv-python (4.1.0.25)
Pillow (6.1.0)
pip (9.0.1)
pkg-resources (0.0.0)
pyparsing (2.4.2)
python-dateutil (2.8.0)
PyYAML (5.1.2)
scipy (1.3.1)
setuptools (39.0.1)
six (1.12.0)
torch (1.2.0)
torchsample (0.1.3, /home/pose3d/src/torchsample)
torchvision (0.4.0)
tqdm (4.34.0)
yacs (0.1.6)
```
created the virtual env with python3.7

**Comment by zh-plus** [comment]
May caused by the index of cuda devices:
```python
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"  # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```

I'm using multi-GPU machine in my environment. Try to change the `os.environ["CUDA_VISIBLE_DEVICES"]` into "0" in `./videopose.py`

**Comment by basicvisual** [comment]
Thanks ! it works very good . Actually smoother than you had experienced and better. I suspect you used a wrong pretrained model that is why you got some fluctuating results. I would like to close this issue and perhaps reach you out for more details . Great work !
