### ISSUE TITLE
Can we execute it in window environment with GPU utilization?

### ISSUE THREAD

**Issue by sajjadafridi** [zh-plus/video-to-pose3D#22]
Hi,

I tried the code to run in window. Everything was fine but the main issue i am facing is that the code doesn't utilize the GPU. I tried each and every possible solution but helpless.
Any idea?

**Comment by zh-plus** [comment]
I'm afraid that I can't provide any idea since I didn't try to run it in windows environment.

Did you check the value of `torch.cuda.is_available()` [here](https://github.com/zh-plus/video-to-pose3D/blob/master/videopose.py#L84)?

**Comment by sajjadafridi** [comment]
> I'm afraid that I can't provide any idea since I didn't try to run it in windows environment.
> 
> Did you check the value of `torch.cuda.is_available()` [here](https://github.com/zh-plus/video-to-pose3D/blob/master/videopose.py#L84)?

yes i debug this line of code. it returns true for this line but still, GPU is not utilizing. Is there any other way to handle this?

**Comment by zh-plus** [comment]
What GPU are you using? And how long did it cost to process this [sample video](https://github.com/zh-plus/video-to-pose3D/blob/master/outputs/kunkun_cut.mp4)?

I'm using Nvidia Tesla V100 to process it, which takes 101.25 seconds. If you're not utilizing any GPU, it's impossible to take less than 20 minutes.

**Comment by sajjadafridi** [comment]
> What GPU are you using? And how long did it cost to process this [sample video](https://github.com/zh-plus/video-to-pose3D/blob/master/outputs/kunkun_cut.mp4)?
> 
> I'm using Nvidia Tesla V100 to process it, which takes 101.25 seconds. If you're not utilizing any GPU, it's impossible to take less than 20 minutes.

Well, I am using Nvidia-GeForce 1080- ti 11gb on ubuntu it works like a charm but on window os it doesn't show any GPU utilization.
I am doing it for live webcam.

**Comment by zh-plus** [comment]
╮（╯＿╰）╭ No idea for that.
