### ISSUE TITLE
是否可以实时3D关节预测？

### ISSUE THREAD

**Issue by Fungus-Light** [zh-plus/video-to-pose3D#23]
请问是否可以在运行过程中实时获取到3D关节的数据？以及是否可以将关节信息导出至外部文件供其他应用使用？

**Comment by zh-plus** [comment]
1. 没有尝试过实时预测，实时预测需要换用causal的模型，如有需要可以参考facebook的[原文档](https://github.com/facebookresearch/VideoPose3D/blob/master/DOCUMENTATION.md#symmetric-convolutions-vs-causal-convolutions)修改代码。
2. 可以导出，具体可以参考这个[issue comment](https://github.com/zh-plus/video-to-pose3D/issues/4#issuecomment-526148380)。
