### ISSUE TITLE
Tensorflow OpenPose implementation

### ISSUE THREAD

**Issue by sebo313** [zh-plus/video-to-pose3D#28]
Hi @zh-plus, i am happy to help you with finalizing the openpose detector. As I am using Anaconda I have problems with installing openpose as Anaconda includes a Protobuf version that is incompatible with Caffe. Therefore I thought it would be easier to use [this tf openpose](https://github.com/ildoonet/tf-pose-estimation) implementation. Finally I could write a conda install file to easily set up the system. What do you think?

**Comment by zh-plus** [comment]
Since the accuracy of openpose is not better than AlphaPose, I'm not planning to implement it. Instead, I'd like to wait for a new SOTA 2d pose estimation method later this year.

**Comment by sebo313** [comment]
Thanks for your comment @zh-plus! 

So I assume you the `duc_se.pth `model is the one with ResNet152 backbone (most accurate regarding [this table](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md))? I looked into Alphapose repo and found a --flip flag which might improve accuracy but its not used in this repo right? 

I am looking for a configuration to get the most accurate **single person** 2D keypoint detection available (no matter how long inference take), any idea on how to improve / add another model for single person 2D?

**Comment by zh-plus** [comment]
1. The [table](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md) is added 3 months ago after I found the `duc_se.pth` model. I can't remember where I found it. I believe there'll be an improvement replacing it with [this model](https://drive.google.com/open?id=1kfyedqyn8exjbbNmYq8XGd2EooQjPtF9).
2. Currently, I'm not catching up with the latest released, fancy papers. Thus I'm afraid that I can not provide any idea on it.

**Comment by sebo313** [comment]
Thank you @zh-plus for the information and your input. I will dive deeper into it and let you know / create PR. Good luck with your thesis!
