### ISSUE TITLE
 Data augmentation to solve "high-speed with low-rate" problem: SLOW-MO

### ISSUE THREAD

**Issue by sebo313** [zh-plus/video-to-pose3D#29]
Hi @zh-plus, I also recently thought of using the [Super-SloMo](https://github.com/avinashpaliwal/Super-SloMo) model to increase fps which  hopefully yields in a more stable + accurate 3D skeleton tracking. Do you already have a pipeline in mind? Something like adding a new flag for setting the desired fps -> preprocess video using Super-SloMo -> feed 2D detector -> 3D ? I am happy to help you implementing it :)

**Comment by zh-plus** [comment]
More or less, SloMo would increase accuracy. However, the Inflated frames will also linearly increase the time cost by IO, 2D detectors and videopose3D. Moreover, the training data from videopose3D is roughly normal 30-60 fps videos. I'm wondering if it can perform well in slow-mo videos.

Although there are concerns above, the slow-mo module is worth trying. It's appreciated if you can implement it and give a PR.

(I'm working on my undergraduate thesis now. It's hard to help a lot.)

**Comment by sebo313** [comment]
I will do a PR as soon as I added it :)
