### ISSUE TITLE
2D keypoints to 3d detector ?

### ISSUE THREAD

**Issue by basicvisual** [zh-plus/video-to-pose3D#3]
Hello 
I have a few following questions, while playing around with your implementation.
Could you tell ,where the 2D keypoints are stored and the `data type` for the 2D detector `hrnet` (which variable exactly). 
Second is where this `2d keypoints` acts as input for the `3d module` ??
Third , is it possible to export the 3d joints with the `x,y,z` co-ordinate to a csv file` per frame for analysis with pandas for example 
`

**Comment by zh-plus** [comment]
1. The data type and format of AlphaPose and HR-Net returned by `keypoints = detector_2d(video_name)` is the same, which is in the shape of (frames, 17, xy) using numpy array.
2. The 2d keypoints is wrapped with `UnchunkedGenerator` and fed into the `evaluate` function, where the 3d `model_pos` take the 2d keypoints as input.
3. The 3d prediction result is transferred from camera space to world space, and then rebased using the following code:
    ```python
    prediction = camera_to_world(prediction, R=rot, t=0)

    # We don't have the trajectory, but at least we can rebase the height
    prediction[:, :, 2] -= np.min(prediction[:, :, 2])
    ```
    After these codes, try to export the `prediction` into csv or something else.

**Comment by basicvisual** [comment]
Thank you ! for your explanation . As i am digging more into the code, i seem to have more questions. 
I am trying to do some kind of post processing of the `2d keypoints` (from SimpleHrNet` repo before and trying to map to your implementation . Following are my questions 

1.  If i remember correctly in implementation of `hrnet` the keypoints was an array in the form of `Nx17x2` where `N` is the number of persons . So for single person it is of the shape `1x17x2` with  x,y being the cartesian co-ordinate and c is the confidence score. 
```
`[x1,y,1c1
x2,y,2,c1, 


x17,y17,c17]
```

I tried to print out the `keypoint` variable but i could not manage to get the required shape  with `x,y,c` 
 per frame , format. 

2. I was trying to save the 2D keypoints per frame in `json` format. I tried to access functions in utilities folder but  was unable to do so . Could you guide me to that ?? 
I tried to use the `split_video` function and add the following, something like 
`frame_number = int(stream.get(cv2.CAP_PROP_POS_FRAMES))`  and tried to access the frame numbers so that i can write them in json in the following format 

```
   with open(os.path.join(log_path, '{0}_keypoints.json'.format(str(frame_number).zfill(12))), 'w') as outfile:
                   json.dump(keypoints, outfile)
```
So i get some output as such 
```
├── 000000000000_keypoints.json
├── 000000000001_keypoints.json
├── 000000000002_keypoints.json
├── 000000000003_keypoints.json
├── 000000000004_keypoints.json
```



3.  Is it possible to have the overlaid skeleton image with 2d skeleton ?? If so how can i save it to a folder. 

4.  Also ,  if i could know the `joint order` for the `prediction` that would be really helpful as i can see the values per frame in a csv file or json . 

Advice / tips would be appreciated.

**Comment by basicvisual** [comment]
Hi Thank you for the answers. I could actually manage for the `2d keypoints` to read out the ` keypoints` and `confidence scores` from your implementation.  in the following 
[preds max vals](   https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/joints_detectors/hrnet/pose_estimation/video.py#L136)

a)However when i tried to dump the values of `prediction` i could not manage to do so . I was wondering how I can get the frames ?? 
b) Could you please let know of the `joint order` of the 3D predictions ??  What maps to what in the output ?

**Comment by zh-plus** [comment]
1. The frame number is `i` from [here](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/joints_detectors/hrnet/pose_estimation/video.py#L119). But the `preds` [here](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/joints_detectors/hrnet/pose_estimation/video.py#L136) contains all the predicted 2d joints from different human since there could be more than one people in that frame. You can see that I only choose the person having the highest score [here](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/joints_detectors/hrnet/pose_estimation/video.py#L147).
2. The joint order can be found [here](https://github.com/facebookresearch/VideoPose3D/issues/57#issuecomment-513628272)

**Comment by basicvisual** [comment]
Thank you , for providing the `joint order` I will note them down. 
I did manage to save all the keypoints from 2d predictions frame by frame. So basically i dumped the keypoints per frame to a json file. 

I was trying to do the same. Dump the `predicted 3d ` keypoints on a frame by frame basis but i could  not manage it . If i understand correctly , you generate the keypoints based on the 2d keypoints detected. 

[3d keypoints](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/videopose.py#L109) seem to be redcited in this step and you do a numpy save . But i igues it is only for one frame right ??

**Comment by zh-plus** [comment]
The 3d keypoints returned by `evaluate` function contains all the generated 3d frames, instead of one frame. It takes all the 2d inputs and a 3d models, and return the 3d keypoints of video based on the input.

**Comment by basicvisual** [comment]
Thank you !

**Comment by basicvisual** [comment]
Hi , as i have a few queries . I was wondering if you were following the `Hrnet` module. It seems the accuracy has improved quite a lot for both multiple people . I was following this repo [simplehrnet](https://github.com/stefanopini/simple-HRNet).  I was wondering if it could be possible to track this repo as base repo and extend the video pose repo ? or is it something not possible . Please let me know your thoughts

**Comment by zh-plus** [comment]
Of course, you can try to use simplehrnet as the 2d detector. What you should do is adding the repo into joints_detectors folder and change the API the same as [here](https://github.com/zh-plus/video-to-pose3D/blob/631328f7d1e42e481a69eb96d9268452d885954a/videopose.py#L39). Don't forget to convert the generated 2d keypoint format into that of AlphaPose.

I would have tried to integrate more accurate 2d detectors. However, I'm afraid that I can't help a lot since I'm focusing on my bachelor's thesis now.

**Comment by basicvisual** [comment]
Thank you ! The easiest for me is to have the input the keypoints as 
a) Clone the simpleHRnet repo to the the `joindetectors` folder .
b) In the simpleHrnet `scripts/live-demo.py`  The keypoints is detected here  [](https://github.com/stefanopini/simple-HRNet/blob/c808af8e2f1b01755e339ab4b70bc5e2a49b5897/scripts/live-demo.py#L64)
c)  Export it is some how or , i am wondering what changes i can make ?? 

And good luck for your thesis !

**Comment by zh-plus** [comment]
I'm not clear about the output format of simplehrnet. But there may be difference between the required input format of Videopose, i.e. the output format of Alphapose. The differences can be the order of joints, the number of joints, et al.

After knowing the difference, a conversion should be performed at the output of simplehrnet, which makes it possible to feed the 2d joints data into Videopose.

Thanks for your wishes.
