### ISSUE TITLE
about the file of data

### ISSUE THREAD

**Issue by lvandoit** [zh-plus/video-to-pose3D#33]
hi:
 Sorry to bother. It is a interesting work, but when i run the file named origin_run.py, it has a error about having not 'data/data_3d_h36m.npz'. So doesn't this file exist in your code? How can i geit it? thanks for yourr work and any reply!@zh-plus

**Comment by zh-plus** [comment]
The `origin_run.py` is just for reference. You should use `videopose.py`.

By the way, 'data/data_3d_h36m.npz' is used for training, which is not included in this repository.
