### ISSUE TITLE
change 3D viewpoint

### ISSUE THREAD

**Issue by hclakk** [zh-plus/video-to-pose3D#34]
Hi,
I want to know if there's a parameter(in degree) in videopose.py to change the 3D result viewpoint from default view?
thanks

**Comment by zh-plus** [comment]
You can change the `azim`  parameter of `render_animation` in https://github.com/zh-plus/video-to-pose3D/blob/b09374082557a6228d14e7d11ef09fa12b25cae8/videopose.py#L129
which can change the "camera position".

**Comment by hclakk** [comment]
Thanks for quick reply
