### ISSUE TITLE
"--vis_fast" or "--viz_fast" flag doesn't exist

### ISSUE THREAD

**Issue by thekryz** [zh-plus/video-to-pose3D#36]
When trying to run the script, it eventually arrives at a point where it shows the following message:

```
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).
```

However, when I try to run the script like this:
```
python videopose.py --vis_fast
```
or like this:
```
python videopose.py --viz_fast
```
I get the message
```
videopose.py: error: unrecognized arguments: --vis_fast
```
or
```
videopose.py: error: unrecognized arguments: --viz_fast
```

What am I doing wrong?

**Comment by smq20181217** [comment]
Add `vis_fast = True` in \joints_detectors\Alphapose\gene_npz.py

**Comment by zh-plus** [comment]
The `vis_fast` option is in [opt.py](https://github.com/zh-plus/video-to-pose3D/blob/master/joints_detectors/Alphapose/opt.py), whose `parse_args()` is called while executing https://github.com/zh-plus/video-to-pose3D/blob/b09374082557a6228d14e7d11ef09fa12b25cae8/joints_detectors/Alphapose/gene_npz.py#L13 However, in `videopose.py`, we use the other `parse_args()` for [argements.py](https://github.com/zh-plus/video-to-pose3D/blob/master/common/arguments.py), which doesn't include `vis_fast` option.

Thus, you can directly set `args.vis_fast = true` anywhere before using `DataWriter` in https://github.com/zh-plus/video-to-pose3D/blob/b09374082557a6228d14e7d11ef09fa12b25cae8/joints_detectors/Alphapose/gene_npz.py#L135

By the way, I recommend inserting `args.vis_fast = true` immediately after retrieving `args` in https://github.com/zh-plus/video-to-pose3D/blob/b09374082557a6228d14e7d11ef09fa12b25cae8/joints_detectors/Alphapose/gene_npz.py#L16
