### ISSUE TITLE
Mapping from Coco keypoints to HM3.6 keypoints?

### ISSUE THREAD

**Issue by sebo361** [zh-plus/video-to-pose3D#37]
Hi @zh-plus, I am wondering where the mapping from the 17 Coco keypoints generated by AlphaPose to the HM3.6 keypoints for inferring the 3D uplifting takes place? It's easy to determine HM3.6 keypoints PELVIS and THORAX from Cocos keypoints `(RHip + LHip) /2` and `(RShoulder + LShoulder) /2` respectively, but how are the HM3.6 SPINE and HEAD keypoints determined? I could not find the code snippet for mapping keypoints in your repo..

**COCO keypoints**
    {0,  "Nose"},
    {1,  "LEye"},
    {2,  "REye"},
    {3,  "LEar"},
    {4,  "REar"},
    {5,  "LShoulder"},
    {6,  "RShoulder"},
    {7,  "LElbow"},
    {8,  "RElbow"},
    {9,  "LWrist"},
    {10, "RWrist"},
    {11, "LHip"},
    {12, "RHip"},
    {13, "LKnee"},
    {14, "Rknee"},
    {15, "LAnkle"},
    {16, "RAnkle"}

**HM3.6 keypoints**
   PELVIS = 0
   R_HIP = 1
   R_KNEE = 2
   R_FOOT = 3
   L_HIP = 4
   L_KNEE = 5
   L_FOOT = 6
   SPINE = 7
   THORAX = 8
   NOSE = 9
   HEAD = 10
   L_SHOULDER = 11
   L_ELBOW = 12
   L_WRIST = 13
   R_SHOULDER = 14
   R_ELBOW = 15
   R_WRIST = 16

**Comment by sebo361** [comment]
Ah i guess i found the answer [here](https://github.com/facebookresearch/VideoPose3D/issues/67#issuecomment-517251616)

**Comment by sebo361** [comment]
Or did you train `pretrained_h36m_detectron_coco.bin` by yourself on Coco keypoints? I thought it's the `pretrained_h36m_cpn.bin` of [FB's VideoPose3D repo](https://github.com/facebookresearch/VideoPose3D) as both pretrained models have the identical file size :)

**Comment by lan786** [comment]
@sebo361  Hi, did  you get your ans? Your comment is valuable and if you already got your ans then kindly explain it. Thanks

**Comment by sebo361** [comment]
Hi @lan786, yes it's written in the Facebook paper. Please check [this issue](https://github.com/facebookresearch/VideoPose3D/issues/67)

**Comment by yuanjianhe32** [comment]
> Hi @lan786, yes it's written in the Facebook paper. Please check [this issue](https://github.com/facebookresearch/VideoPose3D/issues/67)

Hi, i have checked both the issue and the paper , can't seem to find the answer. Can you provide more details ？
