### ISSUE TITLE
Exporting 3d pose to animation in unity or blender ? [extension]

### ISSUE THREAD

**Issue by ns3new** [zh-plus/video-to-pose3D#4]
Hi 
I was wondering if there is a script , that parses out the 3d joints per frame , that can be used for animation purposes or perhaps there is an already exisitng module that does that ? 
/Thanks 
N

**Comment by zh-plus** [comment]
There's a visualization function invoked [here](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/videopose.py#L129), which generate the [animation](https://github.com/zh-plus/video-to-pose3D/blob/master/asset/kunkun_alphapose.gif) using matplotlib. However, unity or blender animation is not provided. 

On the other way, you can save the predicted 3d pose (in numpy array format) after [here](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/videopose.py#L118) where the post-process has been done. And then convert them into the specific(unity or blender) format by your self. 

Contributions of the visualization module are welcomed.

**Comment by ns3new** [comment]
Can i ask you what does this line of code do ?? 

https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/videopose.py#L114

Thanks!

**Comment by zh-plus** [comment]
Rotation part of the extrinsic parameter in 2d scenario, which is used to convert the prediction from camera space into world space. Check out [this](https://www.cs.toronto.edu/pub/psala/VM/camera-parameters.pdf) for more information about the camera parameters.

**Comment by ns3new** [comment]
Thank you !

**Comment by krunal-mirrorar** [comment]
> On the other way, you can save the predicted 3d pose (in numpy array format) after [here](https://github.com/zh-plus/video-to-pose3D/blob/60c0b10482ea3baa69dad9408d1f1132d9e678ee/videopose.py#L118) where the post-process has been done. And then convert them into the specific(unity or blender) format by your self.

As mentioned, I am trying to save predictions in npy file. It would be helpful if you can verify that these predictions are in [x,y,z] order @zh-plus

**Comment by krunal-jain** [comment]
> On the other way, you can save the predicted 3d pose (in numpy array format) after here where the post-process has been done. And then convert them into the specific(unity or blender) format by your self.

As mentioned, I am trying to save predictions in npy file. It would be helpful if you can verify that these predictions are in [x,y,z] order @zh-plus
