### ISSUE TITLE
im_names referenced before assignment

### ISSUE THREAD

**Issue by Adblu** [zh-plus/video-to-pose3D#5]
(pose) D:\PYTHON\pose_detection>python videopose.py
outputs/dance.mp4 --- elapsed time: 3.8129527000000003 s
Traceback (most recent call last):
  File "videopose.py", line 164, in <module>
    inference_video('outputs/dance.mp4', 'alpha_pose')
  File "videopose.py", line 160, in inference_video
    main(args)
  File "videopose.py", line 69, in main
    keypoints = detector_2d(video_name)
  File "D:\PYTHON\pose_detection\joints_detectors\Alphapose\gene_npz.py", line 67, in handle_video
    data_loader = ImageLoader(im_names, batchSize=args.detbatch, format='yolo').start()
UnboundLocalError: local variable 'im_names' referenced before assignment

Do you have any idea why this is happens ?

**Comment by zh-plus** [comment]
The `im_names` is not properly initialized at [here](https://github.com/zh-plus/video-to-pose3D/blob/master/joints_detectors/Alphapose/gene_npz.py#L62). Try to set a breakpoint there and check if there is any bug caused by typo in video path.
