### ISSUE TITLE
Argument 'alpha' can not be treated as a double

### ISSUE THREAD

**Issue by curryanswer** [zh-plus/video-to-pose3D#53]
I run your code on a server, but I can't get output. Could you please help me find out what problems with it?

`the video is 25.051 f/s
Loading YOLO model..
Loading pose model from joints_detectors/Alphapose/models/sppe/duc_se.pth
Start pose estimation...
  0%|                                                                                                                                                                | 0/338 [00:00<?, ?it/s]Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/hedian/anaconda3/envs/videopose3d/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/hedian/anaconda3/envs/videopose3d/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hedian/project/video-to-pose3D/joints_detectors/Alphapose/dataloader.py", line 678, in update
    img = vis_frame(orig_img, result)
  File "/home/hedian/project/video-to-pose3D/joints_detectors/Alphapose/fn.py", line 198, in vis_frame
    img = cv2.addWeighted(bg, transparency, img, 1 - transparency, 0)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'addWeighted'
> Overload resolution failed:
>  - Argument 'alpha' can not be treated as a double
>  - Argument 'alpha' can not be treated as a double

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 338/338 [00:20<00:00, 16.19it/s]
===========================> Rendering remaining images in the queue...
===========================> If this step takes too long, you can enable the --vis_fast flag to use fast rendering (real-time).`

**Comment by zh-plus** [comment]
Check this PR: #49, which should have fixed this issue. Pulling the latest version may help.
