### ISSUE TITLE
Environment Configuration

### ISSUE THREAD

**Issue by curryanswer** [zh-plus/video-to-pose3D#55]
hello！Could you upload the configuration of your environment?
if you use anaconda, you can use this command:
`conda activate yourenv`
`conda list --export > package-list.txt`
Thank you very much!!!!
(I encounter a  problem that ask me to downgrade my python version to 3.6~3.7, because matplotlib=3.1.0 is incompatible with python3.9)

**Comment by zh-plus** [comment]
conda-package-list.txt uploaded.

**Comment by curryanswer** [comment]
> conda-package-list.txt uploaded

Many thanks!!
